import type { Metadata } from "next";

import { Inter as FontSans } from "next/font/google";

import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "@/lib/providers";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          " bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Providers>
          <div className="flex w-full flex-col gap-10">
            <h1 className="text-4xl text-center font-medium mt-10">
              Artist Management System
            </h1>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
